app_version: v4.0.2
capabilities: []
categories:
- media
changelog_url: https://github.com/diced/zipline/releases
date_added: '2025-05-17'
description: Zipline The next generation ShareX / File upload server.
home: https://github.com/diced/zipline
host_mounts: []
icon: https://media.sys.truenas.net/apps/zipline/icons/icon.png
keywords:
- zipline
- media
lib_version: 2.1.27
lib_version_hash: 2139f95ab6f83ded6ff6a0924f3c62b62eb0867180923a1a71f72752b474526d
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: zipline
run_as_context:
- description: Zipline runs as any non-root user.
  gid: 568
  group_name: zipline
  uid: 568
  user_name: zipline
- description: Postgres runs as non-root user.
  gid: 999
  group_name: postgres
  uid: 999
  user_name: postgres
sources:
- https://github.com/diced/zipline
title: Zipline
train: community
version: 1.0.0
