images:
  zipline:
    repository: ghcr.io/diced/zipline
    tag: 4.0.2
  postgres:
    repository: postgres
    tag: "16"

consts:
  zipline_container_name: zipline
  postgres_container_name: postgres
  perms_container_name: permissions
  db_name: zipline
  pg_run_user: 999
  pg_run_group: 999
